# Generated by Django 3.2.15 on 2022-08-25 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredienttorecipe',
            old_name='count',
            new_name='amount',
        ),
    ]
