# Generated by Django 3.2.15 on 2022-08-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram_api', '0003_auto_20220825_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.DurationField(verbose_name='время приготовления'),
        ),
    ]
