# Generated by Django 3.2.15 on 2022-08-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram_api', '0005_alter_recipe_cooking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(verbose_name='время приготовления в минутах'),
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('user', 'subscriber')},
        ),
    ]
